site_name: Tinkerstruct Documentation

theme:
  name: material
  palette:
    primary: grey
    accent: yellow
  logo: assets/logo.png

markdown: kramdown
kramdown:
  parse_block_html: true

extra_css:
  - stylesheets/extra.css
