site_name: Tinkerstruct Documentation

theme:
  name: material
  palette:
    primary: grey
    accent: yellow

markdown: kramdown
kramdown:
  parse_block_html: true

extra_css:
  - stylesheets/extra.css

theme:
  logo: assets/logo.png