site_name: Tinkerstruct Documentation

theme:
  name: material
  palette:
    primary: yellow
    accent: grey
  logo: assets/logo.png

markdown: kramdown
kramdown:
  parse_block_html: true

extra_css:
  - stylesheets/extra.css
