site_name: Tinkerstruct Documentation

theme:
  name: material
  palette:
    primary: white
    accent: gray

markdown: kramdown
kramdown:
  parse_block_html: true

extra_css:
  - stylesheets/extra.css
