site_name: Tinkerstruct Documentation

theme:
  name: material
  scheme:
  theme: readthedocs
  palette:
    primary: amber
    accent: yellow
  logo: assets/logo.png

markdown: kramdown
kramdown:
  parse_block_html: true

extra_css:
  - stylesheets/extra.css
